// games/quickdraw/src/ui/Logs.vue
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';
import { logs } from '../ui';
import { useAutoScroll } from './useAutoscroll';

function formatTimestamp(ms: number): string {
  const date = new Date(ms);

  const hours = date.getHours() % 12;
  const minutes = date.getMinutes().toString().padStart(2, "0");
  const seconds = date.getSeconds().toString().padStart(2, "0");
  const millis = date.getMilliseconds().toString().padStart(3, "0");

  return `${hours}:${minutes}:${seconds}.${millis}`;
}


const { container, onContentUpdated } = useAutoScroll(80);

watch(() => logs.value.length, () => {
  onContentUpdated();
})

</script>

<template>
  <ul ref="container">
    <li v-for="(log, index) in logs" :key="index" class="log" :class="log.source">
      <div class="contents">
        <h3 :class="{ [log.source]: true}">
          <span class="source">{{ log.source }} | </span>
          <span class="frame-number">f{{ log.frame_number }} | </span>
          <span class="timestamp">{{ formatTimestamp(log.timestamp) }}</span>
        </h3>
        <div class="content">
          <p v-if="log.label">{{ log.label }}</p>
          <pre v-if="log.json" class="json">{{ log.json }}</pre>
        </div>
      </div>
    </li>
  </ul>
</template>

<style scoped>
ul {
  width: 94%;
  height: 100%;
  overflow: auto;
}

li {
  margin: 0 0 24px 0;
  list-style: none;
}

h3 {
  font-size: 16px;
  font-weight: 500;
}

.ws {
  color: darkolivegreen;
}

.webrtc {
  color: darkmagenta;
}

.content {
  font-size: 16px;
}

pre {
  margin: 0;
  white-space: pre-wrap;
  word-break: break-word;
  background-color: oldlace;
  padding: 8px;
  border-radius: 4px;
  border: 1px inset lavender;
}
</style>

// packages/web/src/debugui/components/Logs.tsx
import { useSignalEffect } from "@preact/signals";
import { debugState } from "../state.ts";
import { useAutoScroll } from "../hooks/useAutoScroll.ts";
import type { Log } from "../../netcode/logs.ts";

function formatTimestamp(ms: number): string {
  const date = new Date(ms);
  const hours = date.getHours() % 12;
  const minutes = date.getMinutes().toString().padStart(2, "0");
  const seconds = date.getSeconds().toString().padStart(2, "0");
  const millis = date.getMilliseconds().toString().padStart(3, "0");
  return `${hours}:${minutes}:${seconds}.${millis}`;
}

export function Logs() {
  const { containerRef, onContentUpdated } = useAutoScroll(80);
  const logs = debugState.logs.value;

  // Trigger auto-scroll when logs change
  useSignalEffect(() => {
    const _ = debugState.logs.value.length;
    onContentUpdated();
  });

  return (
    <ul className="logs-list" ref={containerRef}>
      {logs.map((log: Log, index: number) => (
        <LogEntry key={index} log={log} />
      ))}
    </ul>
  );
}

function LogEntry({ log }: { log: Log }) {
  return (
    <li className={`log ${log.source}`}>
      <div className="contents">
        <h3 className={log.source}>
          <span className="source">{log.source} | </span>
          {log.match_frame != null ? (
            <span className="frame-number">m{log.match_frame} | </span>
          ) : (
            <span className="frame-number">f{log.frame_number} | </span>
          )}
          <span className="timestamp">{formatTimestamp(log.timestamp)}</span>
        </h3>
        <div className="content">
          {log.label && <p>{log.label}</p>}
          {log.json && (
            <pre className="json">{JSON.stringify(log.json, null, 2)}</pre>
          )}
          {log.packet && <div>{log.packet.size} bytes</div>}
        </div>
      </div>
    </li>
  );
}
